get:
  summary: Get a product by its ID number
  tags:
   - Products
  parameters:
    - name: id
      in: path
      required: true
      description: The id number of the product
      schema:
        type: integer
        example: 1
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Product.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
put:
  summary: Update a product by its ID number
  tags:
   - Products
  parameters:
   - name: id
     in: path
     required: true
     description: The id number of the product
     schema:
      type: integer
      example: 1
  requestBody:
   required: true
   content:
    application/json:
     schema:
      type: object
      properties:
        name:
          type: String
          example: Keyboard
        description:
          type: String
          example: Mechanical Keyboard
        price:
          type: Float
          example: 2.99
        stock:
          type: Integer
          example: 1
  responses:
    '200':
      description: Product updated successfully
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Product.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotLoggedIn.yaml
    '403':
      $ref: ../components/responses/NoPermission.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    
delete:
  summary: Delete a product by its ID number
  tags:
    - Products
  parameters:
    - name: id
      in: path
      required: true
      description: The id number of the product
      schema:
        type: integer
        example: 1
  responses:
    '204':
      description: No Content
      content:
        application/json:
          schema:
            type: object
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotFound.yaml
    '403':
      $ref: ../components/responses/NoPermission.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
  